timeoutLength: 600000 # 10 * 60 * 1000 = 10 minutes
lowVoltage: 11.9

TACTICAL_whitelist:
  - KC1GDW-7
  - W1FN

trackedStations:
  # Digis/iGates
  W1FN-1: Moose Mt
  W1FN-5: Hanover
  W1FN-9: Bath
  N1GMC-1: Dame Hill Rd, Orford
  N1GMC-2: Sunday Mt, Orford
  KB1FDA-1: Corinth

  # Vehicles
  K1EHZ-10: Recovery
  NA1T-9: Ride Manager
  KC1LFU-1: Logistics Coord.
  KC1GDW-9: Bike Tech
  WA1ZCN-11: Trouble
  KC1LFU-2: Rover 1
  K1EHZ-4: Rover 2
  W1TGA-9: Rover 3
