timeoutLength: 600000 # 10 * 60 * 1000 = 10 minutes
lowVoltage: 11.9

TACTICAL_whitelist:
  - KC1GDW-7
  - W1FN

trackedStations:
  # Digis/iGates
  W1FN-1:
  W1FN-3:
  W1FN-5:
  W1FN-6:
  W1FN-7:
  W1FN-8:
  W1FN-9:
  W1FN-10:
  N1GMC-1:
  N1GMC-2:

  # Vehicles
  AE1H-9: Rover 1
  K1EHZ-4: Rover 2
  K1EHZ-2: Recovery
  KC1LFU-6: Rover 3
  NA1T-9: Ride Manager
  KC1LFU-7: Logistics Coordinator
  KC1LFU-8: Dartmouth EMS
  KC1GDW: Bike Tech Van

