TACTICAL_whitelist:
  - KC1GDW-7
  - W1FN

default:
  timeoutLength: 10 minutes
  lowVoltage: 11.9

trackedStations:
  # Digis/iGates
  W1FN-1:
    tactical: Moose Mt
    timeoutLength: 25 minutes
  W1FN-5:
    tactical: Hanover
    timeoutLength: 25 minutes
  W1FN-9:
    tactical: Bath
    timeoutLength: 25 minutes
  N1GMC-1:
    tactical: Dame Hill Rd, Orford
    timeoutLength: 25 minutes
  N1GMC-2:
    tactical: Sunday Mt, Orford
    timeoutLength: 25 minutes
  KB1FDA-1:
    tactical: Corinth
    timeoutLength: 25 minutes

  # Vehicles
  K1EHZ-10: Recovery
  NA1T-9: Ride Manager
  KC1LFU-1: Logistics Coord.
  KC1GDW-9: Bike Tech
  WA1ZCN-11: Trouble
  KC1LFU-2: Rover 1
  K1EHZ-4: Rover 2
  W1TGA-9: Rover 3
