timeoutLength: 600000 # 10 * 60 * 1000 = 10 minutes
lowVoltage: 11.9

TACTICAL_whitelist:
  - KC1GDW-7
  - W1FN

trackedStations:
  # Digis/iGates
  W1FN-1:
  W1FN-3:
  W1FN-5:
  W1FN-6:
  W1FN-7:
  W1FN-8:
  W1FN-9:
  W1FN-10:
  N1GMC-1:
  N1GMC-2:

  # Vehicles
  W1HS-9: Rover SF-1
  KC1LFU-5: Rover 1-2
  KC1LFU-1: Rover 2-1
  KC1LFU-2: Rover 2-3
  N1EMF-7: Rover 3-4
  K1DSP-9: Rover 4-5
  AB1XQ-9: Rover 5-8
  N5IEP-1: Rover 5-6
  KC1BOS-2: Rover 6-7
  K1EHZ-4: Rover 7-8
  KC1LFU-6: Rover 2-8
  KC1LFU-7: Rover 8-2
  KC1LFU-3: Rover FPL
  WB1BRE-14: Metric Rover
  KC1LFU-9: Recovery 1
  W1LKS-9: Recovery 2
  WB1BRE-15: Shuttle 1
  KC1LFU-10: Supply 1
  NA1T-9: Safety 1
  AE1H-9: Trouble 1
  AE1H-8: Trouble 2
